### ISSUE TITLE
Bootstrapping infrastucture fails while launching aws cluster from cloudbreak UI.

### ISSUE THREAD

**Issue by ramprasadxt** [sequenceiq/cloudbreak#1121]
Hi,

I am trying to launch a cluster from cloudbreak-deployment which is deployed in aws

Some details about our deployment,

Cluster: cluster resides in AWS and credentials have been configured accordingly.
resource: 'minviable-aws'
blueprint: 'hdp-small-default'

Cloudbreak was deployed in CentOS7 and no errors appeared during the deployment.

During the 'Bootstrapping infrastructure cluster' step, I checked the cbd logs. It seems like cloudbreak is polling for an API but fails continuously, the message goes as below,

ambassador_1    | 2015/11/13 10:49:17 172.17.0.3:47946 -> node1.node.dc1.consul.:5432cloudbreak_1    | 2015-11-13 10:49:17,079 [threadPoolExecutorDispatcher-8] pollWithTimeout:30 INFO  c.s.c.s.PollingService - [owner:b2f9a0d4-8101-4e0d-8872-9789e67a91df] [type:STACK] [id:50] [name:cloudbreak-development-testing] Polling attempt 207.cloudbreak_1    | 2015-11-13 10:49:17,080 [threadPoolExecutorDispatcher-8] isBootstrapApiAvailable:301 
INFO  c.s.c.o.s.SwarmContainerOrchestrator - [owner:b2f9a0d4-8101-4e0d-8872-9789e67a91df] [type:STACK] [id:50] [name:cloudbreak-development-testing] Checking if docker daemon is available.cloudbreak_1    | 
2015-11-13 10:49:17,120 [threadPoolExecutorDispatcher-8] isBootstrapApiAvailable:308 
WARN  c.s.c.o.s.SwarmContainerOrchestrator - [owner:b2f9a0d4-8101-4e0d-8872-9789e67a91df] [type:STACK] [id:50] [name:cloudbreak-development-testing] Docker api not available: "<html>cloudbreak_1    | <head><title>400 The SSL certificate error</title></head>cloudbreak_1    | <body bgcolor="white">cloudbreak_1    | <center>\<h1>400 Bad Request\</h1></center>cloudbreak_1    | <center>The SSL certificate error</center>cloudbreak_1    | \<hr><center>nginx/1.9.1</center>cloudbreak_1    | </body>cloudbreak_1    | </html>"

After polling for a long time the Bootstrapping step fails and hence, neither Ambari or any other cluster services were started.

I can confirm that the cluster was not started. Because, when I try to enable Autoscaling, the error message in logs was 'cloudbreak_1    | 2015-11-13 10:53:28,346 [http-nio-8080-exec-8] notFound:55 ERROR c.s.c.c.ExceptionControllerAdvice - [owner:cloudbreak] [type:cloudbreakLog] [id:undefined] [name:cb] Ambari server could not be available for the stack.'

And, the error message in the UI says 'Cluster should be available to enable autoscaling on it.'

Any sort of help is highly appreciated, thanks in advance.

Best Regards.

**Comment by ramprasadxt** [comment]
To add more information, I receive the following exception when I click Sync from Cloudbreak UI. It seems like, the ambari IP is null, am I missing a configuration step where I need to specify ambari IP? The Amabari address IP on Cloudbreak UI also says, 'Not Available'

2015-11-16 06:29:17,430 [threadPoolExecutorDispatcher-4] handleClusterSync:591 ERROR c.s.c.c.f.s.SimpleFlowFacade - [owner:b2f9a0d4-8101-4e0d-8872-9789e67a91df] [type:STACK] [id:150] [name:cloudbreak-testing] Exception during cluster start sync!: Cannot connect to Ambari https://null:443/api/v1/
cloudbreak_1    | 2015-11-16 06:29:17,457 [threadPoolExecutorDispatcher-4] consumeError:106 DEBUG c.s.c.c.f.AbstractFlowHandler - [owner:b2f9a0d4-8101-4e0d-8872-9789e67a91df] [type:STACK] [id:150] [name:cloudbreak-testing] Delegating throwable to event's error handler. Event: Event{id=null, headers=null, replyTo=null, key=CLUSTER_SYNC, data=com.sequenceiq.cloudbreak.core.flow.context.StackStatusUpdateContext@993a4c6}, Exception message: {}
cloudbreak_1    | com.sequenceiq.cloudbreak.core.CloudbreakException: com.sequenceiq.ambari.client.AmbariConnectionException: Cannot connect to Ambari https://null:443/api/v1/
cloudbreak_1    | 	at com.sequenceiq.cloudbreak.core.flow.service.SimpleFlowFacade.handleClusterSync(SimpleFlowFacade.java:592) ~[cloudbreak.jar!/:na]
cloudbreak_1    | 	at com.sequenceiq.cloudbreak.core.flow.handlers.ClusterSyncHandler.execute(ClusterSyncHandler.java:17) ~[cloudbreak.jar!/:na]
cloudbreak_1    | 	at com.sequenceiq.cloudbreak.core.flow.AbstractFlowHandler.accept(AbstractFlowHandler.java:48) [cloudbreak.jar!/:na]
cloudbreak_1    | 	at com.sequenceiq.cloudbreak.core.flow.AbstractFlowHandler.accept(AbstractFlowHandler.java:28) [cloudbreak.jar!/:na]
cloudbreak_1    | 	at reactor.bus.EventBus$3.accept(EventBus.java:318) [reactor-bus-2.0.3.RELEASE.jar!/:na]
cloudbreak_1    | 	at reactor.bus.EventBus$3.accept(EventBus.java:311) [reactor-bus-2.0.3.RELEASE.jar!/:na]
cloudbreak_1    | 	at reactor.bus.routing.ConsumerFilteringRouter.route(ConsumerFilteringRouter.java:72) [reactor-bus-2.0.3.RELEASE.jar!/:na]
cloudbreak_1    | 	at reactor.bus.EventBus.accept(EventBus.java:592) [reactor-bus-2.0.3.RELEASE.jar!/:na]
cloudbreak_1    | 	at reactor.bus.EventBus.accept(EventBus.java:64) [reactor-bus-2.0.3.RELEASE.jar!/:na]
cloudbreak_1    | 	at reactor.core.dispatch.AbstractLifecycleDispatcher.route(AbstractLifecycleDispatcher.java:159) [reactor-core-2.0.3.RELEASE.jar!/:na]
cloudbreak_1    | 	at reactor.core.dispatch.MultiThreadDispatcher$MultiThreadTask.run(MultiThreadDispatcher.java:89) [reactor-core-2.0.3.RELEASE.jar!/:na]
cloudbreak_1    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
cloudbreak_1    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
cloudbreak_1    | 	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
cloudbreak_1    | Caused by: com.sequenceiq.ambari.client.AmbariConnectionException: Cannot connect to Ambari https://null:443/api/v1/
cloudbreak_1    | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.7.0_79]
cloudbreak_1    | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[na:1.7.0_79]
cloudbreak_1    | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.7.0_79]
cloudbreak_1    | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[na:1.7.0_79]
cloudbreak_1    | 	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77) ~[groovy-all-2.1.8.jar!/:2.1.8]
cloudbreak_1    | 	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:71) ~[groovy-all-2.1.8.jar!/:2.1.8]
cloudbreak_1    | 	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:81) ~[groovy-all-2.1.8.jar!/:2.1.8]
cloudbreak_1    | 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:190) ~[groovy-all-2.1.8.jar!/:2.1.8]
cloudbreak_1    | 	at com.sequenceiq.ambari.client.AmbariClient.getRawResource(AmbariClient.groovy:1572) ~[ambari-client21-2.1.9.jar!/:na]
cloudbreak_1    | 	at com.sequenceiq.ambari.client.AmbariClient.this$2$getRawResource(AmbariClient.groovy) ~[ambari-client21-2.1.9.jar!/:na]
cloudbreak_1    | 	at com.sequenceiq.ambari.client.AmbariClient$this$2$getRawResource$4.callCurrent(Unknown Source) ~[na:na]
cloudbreak_1    | 	at com.sequenceiq.ambari.client.AmbariClient.getSlurpedResource(AmbariClient.groovy:1585) ~[ambari-client21-2.1.9.jar!/:na]
cloudbreak_1    | 	at com.sequenceiq.ambari.client.AmbariClient.this$2$getSlurpedResource(AmbariClient.groovy) ~[ambari-client21-2.1.9.jar!/:na]
cloudbreak_1    | 	at com.sequenceiq.ambari.client.AmbariClient$this$2$getSlurpedResource$3.callCurrent(Unknown Source) ~[na:na]
cloudbreak_1    | 	at com.sequenceiq.ambari.client.AmbariClient.slurp(AmbariClient.groovy:1627) ~[ambari-client21-2.1.9.jar!/:na]
cloudbreak_1    | 	at com.sequenceiq.ambari.client.AmbariClient.this$2$slurp(AmbariClient.groovy) ~[ambari-client21-2.1.9.jar!/:na]
cloudbreak_1    | 	at com.sequenceiq.ambari.client.AmbariClient$this$2$slurp$1.callCurrent(Unknown Source) ~[na:na]
cloudbreak_1    | 	at com.sequenceiq.ambari.client.AmbariClient.getHosts(AmbariClient.groovy:1671) ~[ambari-client21-2.1.9.jar!/:na]
cloudbreak_1    | 	at com.sequenceiq.ambari.client.AmbariClient.getHostStatuses(AmbariClient.groovy:1065) ~[ambari-client21-2.1.9.jar!/:na]
cloudbreak_1    | 	at com.sequenceiq.cloudbreak.service.cluster.AmbariClusterService.updateClusterMetadata(AmbariClusterService.java:365) ~[cloudbreak.jar!/:na]
cloudbreak_1    | 	at com.sequenceiq.cloudbreak.service.cluster.flow.status.AmbariClusterStatusUpdater.updateClusterStatus(AmbariClusterStatusUpdater.java:49) ~[cloudbreak.jar!/:na]
cloudbreak_1    | 	at com.sequenceiq.cloudbreak.core.flow.service.AmbariClusterFacade.sync(AmbariClusterFacade.java:396) ~[cloudbreak.jar!/:na]
cloudbreak_1    | 	at com.sequenceiq.cloudbreak.core.flow.service.SimpleFlowFacade.handleClusterSync(SimpleFlowFacade.java:589) ~[cloudbreak.jar!/:na]
cloudbreak_1    | 	... 13 common frames omitted
