### ISSUE TITLE
beans name conflicts during Application startup 

### ISSUE THREAD

**Issue by ylvmw** [sequenceiq/cloudbreak#1182]
Hi, 

Another issue I met when start the application from IDE:

```
2015-12-17 16:16:35,310 [main] run:338 [1;31mERROR[0;39m o.s.b.SpringApplication - [owner:spring] [type:springLog] [id:] [name:] Application startup failed
org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'testConfig' for bean class [com.sequenceiq.cloudbreak.service.messages.TestConfig] conflicts with existing, non-compatible bean definition of same name and class [com.sequenceiq.cloudbreak.conf.TestConfig]
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.checkCandidate(ClassPathBeanDefinitionScanner.java:314) ~[spring-context-4.0.7.RELEASE.jar:4.0.7.RELEASE]
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.doScan(ClassPathBeanDefinitionScanner.java:253) ~[spring-context-4.0.7.RELEASE.jar:4.0.7.RELEASE]
```

Could you take a look?

**Comment by mhmxs** [comment]
Sorry for the late answer. Is this issue still alive?
