### ISSUE TITLE
Infrastructure creation failed. Reason: java.net.ConnectException: Connection timed out

### ISSUE THREAD

**Issue by zhengbo0** [sequenceiq/cloudbreak#1506]
When I create the cluster, always throw this error：
``` 
cloudbreak_1 | 2016-04-25 12:28:19,377 [reactorDispatcher-4] getResourceDefinition:34 INFO  c.s.c.s.s.r.d.ResourceDefinitionService - [owner:32e77b87-fc16-4230-b74c-22c463cbde99] [type:STACK] [id:12] [name:pppppppp] Resource property definition: ResourceDefinitionResult{definition='{"values":[{"name":"userName","type":"String","encrypted":true},{"name":"password","type":"String","encrypted":true},{"name":"endpoint","type":"String"},{"name":"keystoneVersion","type":"String"}],"selectors":[{"name":"cb-keystone-v2","values":[{"name":"tenantName","type":"String"}]},{"name":"cb-keystone-v3","values":[{"name":"userDomain","type":"String"},{"name":"keystoneAuthScope","type":"String"}]},{"name":"cb-keystone-v3-default-scope","parent":"cb-keystone-v3","values":[]},{"name":"cb-keystone-v3-domain-scope","parent":"cb-keystone-v3","values":[{"name":"domainName","type":"String"}]},{"name":"cb-keystone-v3-project-scope","parent":"cb-keystone-v3","values":[{"name":"projectDomainName","type":"String"},{"name":"projectName","type":"String"}]}]}'}
cloudbreak_1 | 2016-04-25 12:28:19,399 [reactorDispatcher-4] getImage:57 DEBUG c.s.c.s.i.ImageService - [owner:32e77b87-fc16-4230-b74c-22c463cbde99] [type:STACK] [id:12] [name:pppppppp] Image found! stackId: 12, component: Component{id=12, componentType=IMAGE, name='IMAGE'}
cloudbreak_1 | 2016-04-25 12:28:19,414 [reactorDispatcher-4] handleStackCreationFailure:152 ERROR c.s.c.c.f.s.p.a.StackCreationService - [owner:32e77b87-fc16-4230-b74c-22c463cbde99] [type:STACK] [id:12] [name:pppppppp] Error during stack creation flow:
cloudbreak_1 | org.openstack4j.api.exceptions.ConnectionException: java.net.ConnectException: Connection timed out
cloudbreak_1 | 	at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:58) ~[openstack4j-jersey2-2.0.10-siq01.jar!/:na]
cloudbreak_1 | 	at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.execute(HttpExecutorServiceImpl.java:33) ~[openstack4j-jersey2-2.0.10-siq01.jar!/:na]
cloudbreak_1 | 	at org.openstack4j.core.transport.internal.HttpExecutor.execute(HttpExecutor.java:51) ~[openstack4j-2.0.10-siq01.jar!/:na]
...........
cloudbreak_1 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
cloudbreak_1 | 	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
cloudbreak_1 | Caused by: javax.ws.rs.ProcessingException: java.net.ConnectException: Connection timed out
cloudbreak_1 | 	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:287) ~[jersey-client-2.22.1.jar!/:na]
cloudbreak_1 | 	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:255) ~[jersey-client-2.22.1.jar!/:na]

cloudbreak_1 | 	at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.invokeRequest(HttpExecutorServiceImpl.java:65) ~[openstack4j-jersey2-2.0.10-siq01.jar!/:na]
cloudbreak_1 | 	at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:56) ~[openstack4j-jersey2-2.0.10-siq01.jar!/:na]
cloudbreak_1 | 	... 32 common frames omitted
cloudbreak_1 | Caused by: java.net.ConnectException: Connection timed out
cloudbreak_1 | 	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.7.0_79]
cloudbreak_1 | 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339) ~[na:1.7.0_79]

cloudbreak_1 | 	... 44 common frames omitted
cloudbreak_1 | 2016-04-25 12:28:19,415 [reactorDispatcher-4] fireEventAndLog:203 DEBUG c.s.c.c.f.s.p.a.StackCreationService - [owner:32e77b87-fc16-4230-b74c-22c463cbde99] [type:STACK] [id:12] [name:pppppppp] STACK_INFRASTRUCTURE_CREATE_FAILED [STACK_FLOW_STEP]. ```

**Comment by zhengbo0** [comment]
@lalyos
@akanto
@bbihari
@@schfeca75
@lpuskas
@matyix
@biharitomi
@oleewere
@keyki
@jenkins-sequenceiq
@doktoric
@2martonsereg
