### ISSUE TITLE
cloudbreak Development can not start cloudbreak in idea 

### ISSUE THREAD

**Issue by bendan123812** [sequenceiq/cloudbreak#1512]
**hi
Thank you for attention to my problem !
I follow the instructions of the site http://sequenceiq.com/cloudbreak-docs/latest/development/
and build the development environment of cloudbreak。

But，finally I can not start cloudbreak in idea . I look the log and then I find the cbdb can not connection.

this is the log:**

Caused by: org.apache.ibatis.migration.MigrationException: Error executing command.  Cause: org.apache.ibatis.migration.MigrationException: Could not create SqlRunner. Cause: org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.apache.ibatis.migration.operations.UpOperation.operate(UpOperation.java:64) ~[mybatis-migrations-3.2.0.jar:3.2.0]
	at com.sequenceiq.cloudbreak.conf.DatabaseMigrationConfig.databaseUpMigration(DatabaseMigrationConfig.java:57) ~[main/:na]
	at com.sequenceiq.cloudbreak.conf.DatabaseMigrationConfig$$EnhancerBySpringCGLIB$$cc973486.CGLIB$databaseUpMigration$0(<generated>) ~[main/:na]
	at com.sequenceiq.cloudbreak.conf.DatabaseMigrationConfig$$EnhancerBySpringCGLIB$$cc973486$$FastClassBySpringCGLIB$$e944ab1f.invoke(<generated>) ~[main/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:355) ~[spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at com.sequenceiq.cloudbreak.conf.DatabaseMigrationConfig$$EnhancerBySpringCGLIB$$cc973486.databaseUpMigration(<generated>) ~[main/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_67]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_67]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_67]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_67]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	... 167 common frames omitted
Caused by: org.apache.ibatis.migration.MigrationException: Could not create SqlRunner. Cause: org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.apache.ibatis.migration.operations.DatabaseOperation.getSqlRunner(DatabaseOperation.java:76) ~[mybatis-migrations-3.2.0.jar:3.2.0]
	at org.apache.ibatis.migration.operations.DatabaseOperation.changelogExists(DatabaseOperation.java:61) ~[mybatis-migrations-3.2.0.jar:3.2.0]
	at org.apache.ibatis.migration.operations.UpOperation.operate(UpOperation.java:38) ~[mybatis-migrations-3.2.0.jar:3.2.0]
	... 178 common frames omitted
Caused by: org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:207) ~[postgresql-9.3-1101-jdbc41.jar:na]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64) ~[postgresql-9.3-1101-jdbc41.jar:na]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:138) ~[postgresql-9.3-1101-jdbc41.jar:na]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29) ~[postgresql-9.3-1101-jdbc41.jar:na]
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21) ~[postgresql-9.3-1101-jdbc41.jar:na]
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31) ~[postgresql-9.3-1101-jdbc41.jar:na]
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24) ~[postgresql-9.3-1101-jdbc41.jar:na]
	at org.postgresql.Driver.makeConnection(Driver.java:410) ~[postgresql-9.3-1101-jdbc41.jar:na]
	at org.postgresql.Driver.connect(Driver.java:280) ~[postgresql-9.3-1101-jdbc41.jar:na]
	at org.springframework.jdbc.datasource.SimpleDriverDataSource.getConnectionFromDriver(SimpleDriverDataSource.java:140) ~[spring-jdbc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnectionFromDriver(AbstractDriverBasedDataSource.java:155) ~[spring-jdbc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnection(AbstractDriverBasedDataSource.java:120) ~[spring-jdbc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.apache.ibatis.migration.DataSourceConnectionProvider.getConnection(DataSourceConnectionProvider.java:19) ~[mybatis-migrations-3.2.0.jar:3.2.0]
	at org.apache.ibatis.migration.operations.DatabaseOperation.getSqlRunner(DatabaseOperation.java:74) ~[mybatis-migrations-3.2.0.jar:3.2.0]
	... 180 common frames omitted
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.7.0_67]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339) ~[na:1.7.0_67]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200) ~[na:1.7.0_67]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182) ~[na:1.7.0_67]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.7.0_67]
	at java.net.Socket.connect(Socket.java:579) ~[na:1.7.0_67]
	at java.net.Socket.connect(Socket.java:528) ~[na:1.7.0_67]
	at org.postgresql.core.PGStream.<init>(PGStream.java:60) ~[postgresql-9.3-1101-jdbc41.jar:na]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:101) ~[postgresql-9.3-1101-jdbc41.jar:na]
	... 193 common frames omitted

this is my container status :
![image](https://cloud.githubusercontent.com/assets/6983824/14848989/2f424534-0ca3-11e6-86cf-b75c45816ad0.png)
![image](https://cloud.githubusercontent.com/assets/6983824/14849018/51a890b0-0ca3-11e6-8320-7c4eb96fc6be.png)
![image](https://cloud.githubusercontent.com/assets/6983824/14849064/84c95a38-0ca3-11e6-868e-ed9cbb8a95bc.png)

can you help me ?

**Comment by bendan123812** [comment]
![image](https://cloud.githubusercontent.com/assets/6983824/14849227/69d9435e-0ca4-11e6-8d3b-781bf4fada20.png)

this is my idea configuration

**Comment by schfeca75** [comment]
Hi @bendan123812,

What OS do you use? MacOS or Linux?

**Comment by bendan123812** [comment]
Hi @schfeca75 
centos 7

**Comment by schfeca75** [comment]
The local development was only tested in MacOS with boot2docker.

The ip address which you set in the idea (192.168.216.130) is your computer ip address?

You may use the ip address of the virtual network interface named 'docker0'.

**Comment by bendan123812** [comment]
many thanks @schfeca75 
192.168.216.130 is my computer ip address.
I fix it by change 192.168.216.130 to my docker0 ip address 172.17.0.1

thank you very much !

**Comment by schfeca75** [comment]
Your welcome!
