### ISSUE TITLE
Azure Cluster Creation Fails

### ISSUE THREAD

**Issue by klezalaise** [sequenceiq/cloudbreak#1563]
Hi,

I can't create a cluster on Azure. This operation with the same credential worked with cloudbreak 1.2.2 but not with the last master version.

The events : 
```
17/5/2016 06:56:12 newtest - update in progress: Infrastructure creation failed. Reason: com.microsoft.azure.storage.StorageException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
17/5/2016 06:56:12 newtest - update in progress: Infrastructure creation failed. Reason: com.microsoft.azure.storage.StorageException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
17/5/2016 06:56:12 newtest - create failed: Infrastructure creation failed. Reason: com.microsoft.azure.storage.StorageException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
17/5/2016 06:56:12 newtest - create failed: Infrastructure creation failed. Reason: com.microsoft.azure.storage.StorageException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
```

The complete error logs : 
```
cloudbreak_1 | com.sequenceiq.cloudbreak.cloud.exception.CloudConnectorException: com.microsoft.azure.storage.StorageException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
cloudbreak_1 |  at com.sequenceiq.cloudbreak.cloud.arm.ArmSetup.prepareImage(ArmSetup.java:86) ~[cloud-arm-1.2.5.jar!/:na]
cloudbreak_1 |  at com.sequenceiq.cloudbreak.cloud.handler.PrepareImageHandler.accept(PrepareImageHandler.java:46) ~[cloud-reactor-1.2.5.jar!/:na]
cloudbreak_1 |  at com.sequenceiq.cloudbreak.cloud.handler.PrepareImageHandler.accept(PrepareImageHandler.java:21) ~[cloud-reactor-1.2.5.jar!/:na]
cloudbreak_1 |  at sun.reflect.GeneratedMethodAccessor250.invoke(Unknown Source) ~[na:na]
cloudbreak_1 |  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
cloudbreak_1 |  at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
cloudbreak_1 |  at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302) ~[spring-aop-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
cloudbreak_1 |  at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) ~[spring-aop-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
cloudbreak_1 |  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
cloudbreak_1 |  at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:52) ~[spring-aop-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
cloudbreak_1 |  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
cloudbreak_1 |  at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
cloudbreak_1 |  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
cloudbreak_1 |  at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208) ~[spring-aop-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
cloudbreak_1 |  at com.sun.proxy.$Proxy199.accept(Unknown Source) ~[na:na]
cloudbreak_1 |  at reactor.bus.EventBus$3.accept(EventBus.java:317) [reactor-bus-2.0.7.RELEASE.jar!/:na]
cloudbreak_1 |  at reactor.bus.EventBus$3.accept(EventBus.java:310) [reactor-bus-2.0.7.RELEASE.jar!/:na]
cloudbreak_1 |  at reactor.bus.routing.ConsumerFilteringRouter.route(ConsumerFilteringRouter.java:72) [reactor-bus-2.0.7.RELEASE.jar!/:na]
cloudbreak_1 |  at reactor.bus.routing.TraceableDelegatingRouter.route(TraceableDelegatingRouter.java:51) [reactor-bus-2.0.7.RELEASE.jar!/:na]
cloudbreak_1 |  at reactor.bus.EventBus.accept(EventBus.java:591) [reactor-bus-2.0.7.RELEASE.jar!/:na]
cloudbreak_1 |  at reactor.bus.EventBus.accept(EventBus.java:63) [reactor-bus-2.0.7.RELEASE.jar!/:na]
cloudbreak_1 |  at reactor.core.dispatch.AbstractLifecycleDispatcher.route(AbstractLifecycleDispatcher.java:160) [reactor-core-2.0.7.RELEASE.jar!/:na]
cloudbreak_1 |  at reactor.core.dispatch.MultiThreadDispatcher$MultiThreadTask.run(MultiThreadDispatcher.java:74) [reactor-core-2.0.7.RELEASE.jar!/:na]
cloudbreak_1 |  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
cloudbreak_1 |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
cloudbreak_1 |  at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
cloudbreak_1 | Caused by: com.microsoft.azure.storage.StorageException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
cloudbreak_1 |  at com.microsoft.azure.storage.StorageException.translateFromHttpStatus(StorageException.java:175) ~[azure-storage-4.0.0.jar!/:na]
cloudbreak_1 |  at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:94) ~[azure-storage-4.0.0.jar!/:na]
cloudbreak_1 |  at com.microsoft.azure.storage.core.StorageRequest.materializeException(StorageRequest.java:305) ~[azure-storage-4.0.0.jar!/:na]
cloudbreak_1 |  at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:175) ~[azure-storage-4.0.0.jar!/:na]
cloudbreak_1 |  at com.microsoft.azure.storage.blob.CloudBlobContainer.exists(CloudBlobContainer.java:717) ~[azure-storage-4.0.0.jar!/:na]
cloudbreak_1 |  at com.microsoft.azure.storage.blob.CloudBlobContainer.createIfNotExists(CloudBlobContainer.java:328) ~[azure-storage-4.0.0.jar!/:na]
cloudbreak_1 |  at com.microsoft.azure.storage.blob.CloudBlobContainer.createIfNotExists(CloudBlobContainer.java:304) ~[azure-storage-4.0.0.jar!/:na]
cloudbreak_1 |  at com.microsoft.azure.storage.blob.CloudBlobContainer$createIfNotExists.call(Unknown Source) ~[na:na]
cloudbreak_1 |  at com.sequenceiq.cloud.azure.client.AzureRMClient.createContainerInStorage(AzureRMClient.groovy:270) ~[azure-rest-client-0.1.56.jar!/:na]
cloudbreak_1 |  at com.sequenceiq.cloudbreak.cloud.arm.ArmSetup.prepareImage(ArmSetup.java:79) ~[cloud-arm-1.2.5.jar!/:na]
cloudbreak_1 |  ... 25 common frames omitted
```

cbd doctors : 

```
===> Deployer doctor: Checks your environment, and reports a diagnose.
uname: Linux localhost.localdomain 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
local version:1.3.0-master-21fe5db
latest release:1.2.2
docker command exists: OK
docker client version: 1.11.1
docker client version: 1.11.1
ping 8.8.8.8 on host: OK
ping github.com on host: OK
ping 8.8.8.8 in container: OK
ping github.com in container: OK
```

I use the same blueprint, network( basic azure network already provided in cloudbreak) for cloudbreak 1.2.2 and cloudbreak master.

**Comment by mhmxs** [comment]
Hi @klezalaise,

it seems i won this issue :D So i couldn't reproduce on latest master Cloudbreak. But sometimes deployer has a small delay. Could you please share which cloudbreak container do you use?

For me:
```
$ grep sequenceiq/cloudbreak: docker-compose.yml
    image: sequenceiq/cloudbreak:1.2.5
```

**Comment by klezalaise** [comment]
Hi,

I have the same container :

 grep sequenceiq/cloudbreak docker-compose.yml
    image: sequenceiq/cloudbreak:1.2.5


2016-05-17 16:53 GMT+02:00 Richard Kovacs <notifications@github.com>:

**Comment by mhmxs** [comment]
I tried my best, but i couldn't reproduce, i tried with local hdfs and wasb too.

**Comment by klezalaise** [comment]
Is there something different with azure between the master version and
1.2.2 version that could explained the failure ? Maybe there is something I
need to configure in the master version ?


2016-05-18 8:55 GMT+02:00 Richard Kovacs <notifications@github.com>:

**Comment by mhmxs** [comment]
First i tested it on the latest master, but 2nd-4th tests were running on stock 1.3.0-master-21fe5db. All clusters created as well. Did you only change the deployer version without any change related to credential?

**Comment by klezalaise** [comment]
Yes I only changed the deployer doing :
cbd update master
cbd start



2016-05-18 10:06 GMT+02:00 Richard Kovacs <notifications@github.com>:

**Comment by mhmxs** [comment]
Ok, so i caught the problem by decreasing my system time with ~38 min. The only difference is for me it is also failed on 1.2.2. Could you please check your time settings where cloudbreak deployer containers are running?

**Comment by klezalaise** [comment]
You were right, my vm didn't have the right time set. I changed it and restart cloudbreak. It works as expected.
Thank you
