### ISSUE TITLE
java.lang.NullPointerException: null when creating clusters with openstack

### ISSUE THREAD

**Issue by huazi1988** [sequenceiq/cloudbreak#2235]
I install cloudbreak according to http://sequenceiq.com/cloudbreak-docs/latest/onprem/#install-cloudbreak-deployer. The cbd version is 1.6.2 and cbd doctor tells everying is OK. My openstack version is mitaka. When i deploy a hadoop cluster by cloudbreak with openstack native API not heat, erros as follows:
cloudbreak_1   | 2017-02-08 07:34:54,672 [reactorDispatcher-8] accept:85 ERROR c.s.c.c.h.TerminateStackHandler - [owner:0661af51-ca31-498f-aaa4-1509d012531b] [type:STACK] [id:42] [name:myasdfsadf] Failed to handle TerminateStackRequest: {}
cloudbreak_1   | java.lang.NullPointerException: null
cloudbreak_1   | 	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:210)
cloudbreak_1   | 	at org.openstack4j.openstack.identity.internal.TenantServiceImpl.getByName(TenantServiceImpl.java:34)
cloudbreak_1   | 	at com.sequenceiq.cloudbreak.cloud.openstack.nativ.context.OpenStackContextBuilder.contextInit(OpenStackContextBuilder.java:46)
cloudbreak_1   | 	at com.sequenceiq.cloudbreak.cloud.openstack.nativ.context.OpenStackContextBuilder.contextInit(OpenStackContextBuilder.java:27)
cloudbreak_1   | 	at com.sequenceiq.cloudbreak.cloud.template.AbstractResourceConnector.terminate(AbstractResourceConnector.java:80)
cloudbreak_1   | 	at com.sequenceiq.cloudbreak.cloud.handler.TerminateStackHandler.accept(TerminateStackHandler.java:57)
cloudbreak_1   | 	at com.sequenceiq.cloudbreak.cloud.handler.TerminateStackHandler.accept(TerminateStackHandler.java:32)
cloudbreak_1   | 	at sun.reflect.GeneratedMethodAccessor234.invoke(Unknown Source)
cloudbreak_1   | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
cloudbreak_1   | 	at java.lang.reflect.Method.invoke(Method.java:498)
cloudbreak_1   | 	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
cloudbreak_1   | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
cloudbreak_1   | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
cloudbreak_1   | 	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:52)
cloudbreak_1   | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
cloudbreak_1   | 	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
cloudbreak_1   | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
cloudbreak_1   | 	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
cloudbreak_1   | 	at com.sun.proxy.$Proxy209.accept(Unknown Source)
cloudbreak_1   | 	at reactor.bus.EventBus$3.accept(EventBus.java:317)
cloudbreak_1   | 	at reactor.bus.EventBus$3.accept(EventBus.java:310)
cloudbreak_1   | 	at reactor.bus.routing.ConsumerFilteringRouter.route(ConsumerFilteringRouter.java:72)
cloudbreak_1   | 	at reactor.bus.routing.TraceableDelegatingRouter.route(TraceableDelegatingRouter.java:51)
cloudbreak_1   | 	at reactor.bus.EventBus.accept(EventBus.java:591)
cloudbreak_1   | 	at reactor.bus.EventBus.accept(EventBus.java:63)
cloudbreak_1   | 	at reactor.core.dispatch.AbstractLifecycleDispatcher.route(AbstractLifecycleDispatcher.java:160)
cloudbreak_1   | 	at reactor.core.dispatch.MultiThreadDispatcher$MultiThreadTask.run(MultiThreadDispatcher.java:74)
cloudbreak_1   | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
cloudbreak_1   | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
cloudbreak_1   | 	at java.lang.Thread.run(Thread.java:745)
cloudbreak_1   | 2017-02-08 07:34:54,672 [reactorDispatcher-8] accept:70 DEBUG c.s.c.c.f.Flow2Handler - [owner:0661af51-ca31-498f-aaa4-1509d012531b] [type:STACK] [id:42] [name:myasdfsadf] flow control event arrived: key: TERMINATESTACKRESULT_ERROR, flowid: ba302879-3d9b-4302-a5e2-ceb6c06f77e5, payload: CloudPlatformResult{status=FAILED, statusReason='Stack termination failed.', errorDetails=java.lang.NullPointerException, request=TerminateStackRequest{, cloudResources=[]}}

Any instructions and comments is welcome. 
Thanks.

**Comment by doktoric** [comment]
as I see you just created the credential without tenant id. Could you please provide some details regarding your credential? Did you created without tenantid?
