### ISSUE TITLE
Unable to start sequenceiq/cloudbreak 

### ISSUE THREAD

**Issue by Vishalkale0409** [sequenceiq/cloudbreak#420]
Hi, I am not able to start sequenceiq/cloudbreak because of following error.

Using default password for application endpoints: 16b2fc4e-816c-47c3-b523-5376924e3944
2015-01-23 07:00:03,079 [localhost-startStop-1] <init>:61 INFO  o.s.u.f.SpringTemplateLoader - [owner:spring] [type:springLog] [id:] [name:] SpringTemplateLoader for FreeMarker: using resource loader [org.springframework.core.io.DefaultResourceLoader@757c21b8] and template loader path [classpath:/]
2015-01-23 07:00:05,308 [Tomcat-startStop-1] log:185 ERROR o.a.c.c.ContainerBase - [owner:spring] [type:springLog] [id:] [name:] A child container failed during start
java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].StandardContext[]]
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) [na:1.7.0_65]
        at java.util.concurrent.FutureTask.get(FutureTask.java:188) [na:1.7.0_65]
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:1123) ~[tomcat-embed-core-7.0.52.jar!/:7.0.52]
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:799) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_65]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_65]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_65]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_65]
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].StandardContext[]]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
        ... 6 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire method: public void org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration.setFilterChainProxySecurityConfigurer(org.springframework.security.config.annotation.ObjectPostProcessor,java.util.List) throws java.lang.Exception; nested exception is org.springframework.beans.factory.BeanExpressionException: Expression parsing failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.security.oauth2.config.annotation.web.configuration.ResourceServerConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.springframework.security.oauth2.provider.token.ResourceServerTokenServices org.springframework.security.oauth2.config.annotation.web.configuration.ResourceServerConfiguration.tokenServices; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'securityConfig.ResourceServerConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.sequenceiq.cloudbreak.service.user.UserDetailsService com.sequenceiq.cloudbreak.conf.SecurityConfig$ResourceServerConfiguration.userDetailsService; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'remoteUserDetailsService': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.springframework.web.client.RestOperations com.sequenceiq.cloudbreak.service.user.RemoteUserDetailsService.restTemplate; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'appConfig': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private java.util.List com.sequenceiq.cloudbreak.conf.AppConfig.provisionSetups; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gccProvisionSetup': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.sequenceiq.cloudbreak.service.stack.connector.gcc.GccStackUtil com.sequenceiq.cloudbreak.service.stack.connector.gcc.GccProvisionSetup.gccStackUtil; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gccStackUtil': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private java.lang.String com.sequenceiq.cloudbreak.service.stack.connector.gcc.GccStackUtil.sourceImagePath; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'cb.gcp.source.image.path' in string value "${cb.gcp.source.image.path}"

can someone please help with it?

**Comment by doktoric** [comment]
the answer is in your stacktrace :)
Could not resolve placeholder 'cb.gcp.source.image.path' in string value "${cb.gcp.source.image.path}"
Please add as environment  variable: 
-Dcb.gcp.source.image.path=sequenceiqimage/sequenceiq-ambari17-consul.image.tar.gz
