### ISSUE TITLE
GCP cluster fails creating Snamenode

### ISSUE THREAD

**Issue by desaiak** [sequenceiq/cloudbreak#467]
While creating 1+10+10 Lambda-architecture (blueprint) cluster, the creation fails at Snamenode step in HDFS startup. Usually is fixed when restarting HDFS using Ambari but sometime it does not.

Error from Cloudbreak:

February 13, 2015 1:15:24 PM EST gcc01 - create in progress: Creation of cluster infrastructure has started on the cloud provider.
February 13, 2015 1:15:24 PM EST gcc01 - requested: Creation of cluster infrastructure has been requested.
February 13, 2015 1:19:01 PM EST gcc01 - available: Cluster infrastructure and ambari are available on the cloud. AMBARI_IP:104.154.66.39
February 13, 2015 1:19:02 PM EST gcc01 - update in progress: Building of cluster has been started.
February 13, 2015 1:25:30 PM EST gcc01 - available: Cluster installation failed. Error: Ambari operation failed: [component: 'CLUSTER_INSTALL', requestID: '1']

Error from node log:

2015-02-13 13:43:24,296 INFO  http.HttpServer2 (HttpServer2.java:start(830)) - HttpServer.start() threw a non Bind IOException
java.net.BindException: Port in use: gcc01-17-1423851404221.node.consul:50090
        at org.apache.hadoop.http.HttpServer2.openListeners(HttpServer2.java:891)
        at org.apache.hadoop.http.HttpServer2.start(HttpServer2.java:827)
        at org.apache.hadoop.hdfs.server.namenode.SecondaryNameNode.initialize(SecondaryNameNode.java:276)
        at org.apache.hadoop.hdfs.server.namenode.SecondaryNameNode.<init>(SecondaryNameNode.java:192)
        at org.apache.hadoop.hdfs.server.namenode.SecondaryNameNode.main(SecondaryNameNode.java:671)
Caused by: java.net.BindException: Cannot assign requested address
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:444)
        at sun.nio.ch.Net.bind(Net.java:436)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at org.mortbay.jetty.nio.SelectChannelConnector.open(SelectChannelConnector.java:216)
        at org.apache.hadoop.http.HttpServer2.openListeners(HttpServer2.java:886)
        ... 4 more
2015-02-13 13:43:24,428 FATAL namenode.SecondaryNameNode (SecondaryNameNode.java:main(673)) - Failed to start secondary namenode
java.net.BindException: Port in use: gcc01-17-1423851404221.node.consul:50090
        at org.apache.hadoop.http.HttpServer2.openListeners(HttpServer2.java:891)
        at org.apache.hadoop.http.HttpServer2.start(HttpServer2.java:827)
        at org.apache.hadoop.hdfs.server.namenode.SecondaryNameNode.initialize(SecondaryNameNode.java:276)
        at org.apache.hadoop.hdfs.server.namenode.SecondaryNameNode.<init>(SecondaryNameNode.java:192)
        at org.apache.hadoop.hdfs.server.namenode.SecondaryNameNode.main(SecondaryNameNode.java:671)
Caused by: java.net.BindException: Cannot assign requested address
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:444)
        at sun.nio.ch.Net.bind(Net.java:436)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at org.mortbay.jetty.nio.SelectChannelConnector.open(SelectChannelConnector.java:216)
        at org.apache.hadoop.http.HttpServer2.openListeners(HttpServer2.java:886)
        ... 4 more
2015-02-13 13:43:24,430 INFO  util.ExitUtil (ExitUtil.java:terminate(124)) - Exiting with status 1
2015-02-13 13:43:24,435 INFO  namenode.SecondaryNameNode (StringUtils.java:run(659)) - SHUTDOWN_MSG: 
/************************************************************
SHUTDOWN_MSG: Shutting down SecondaryNameNode at gcc01-11-1423851402933.node.consul/10.0.0.49
************************************************************/

When checking port settings I do not see anything using 50090:

bash-4.1# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address               Foreign Address             State       PID/Program name   
tcp        0      0 10.0.0.49:3888              0.0.0.0:*                   LISTEN      -                   
tcp        0      0 0.0.0.0:8660                0.0.0.0:*                   LISTEN      -                   
tcp        0      0 0.0.0.0:22                  0.0.0.0:*                   LISTEN      -                   
tcp        0      0 0.0.0.0:13562               0.0.0.0:*                   LISTEN      -                   
tcp        0      0 0.0.0.0:50010               0.0.0.0:*                   LISTEN      -                   
tcp        0      0 0.0.0.0:50075               0.0.0.0:*                   LISTEN      -                   
tcp        0      0 0.0.0.0:8670                0.0.0.0:*                   LISTEN      -                   
tcp        0      0 0.0.0.0:53919               0.0.0.0:*                   LISTEN      -                   
tcp        0      0 0.0.0.0:2181                0.0.0.0:*                   LISTEN      -                   
tcp        0      0 0.0.0.0:8040                0.0.0.0:*                   LISTEN      -                   
tcp        0      0 0.0.0.0:8042                0.0.0.0:*                   LISTEN      -                   
tcp        0      0 0.0.0.0:8010                0.0.0.0:*                   LISTEN      -                   
tcp        0      0 0.0.0.0:45454               0.0.0.0:*                   LISTEN      -                   
tcp        0      0 :::8400                     :::*                        LISTEN      -                   
tcp        0      0 :::8500                     :::*                        LISTEN      -                   
tcp        0      0 :::53                       :::*                        LISTEN      -                   
tcp        0      0 :::22                       :::*                        LISTEN      -                   
tcp        0      0 :::8301                     :::*                        LISTEN      -                   
udp        0      0 0.0.0.0:68                  0.0.0.0:*                               -                   
udp        0      0 172.17.42.1:123             0.0.0.0:*                               -                   
udp        0      0 10.0.0.49:123               0.0.0.0:*                               -                   
udp        0      0 127.0.0.1:123               0.0.0.0:*                               -                   
udp        0      0 0.0.0.0:123                 0.0.0.0:*                               -                   
udp        0      0 0.0.0.0:8583                0.0.0.0:*                               -                   
udp        0      0 0.0.0.0:59157               0.0.0.0:*                               -                   
udp        0      0 :::53                       :::*                                    -                   
udp        0      0 :::8301                     :::*                                    -                   
udp        0      0 :::123                      :::*                                    -                   
udp        0      0 :::26364                    :::*                                    -                   
bash-4.1# netstat -tupln | grep :50090

**Comment by keyki** [comment]
As I checked I have the same error, but if you execute a `hostname` command you'll see that the SN tries to bind to a port on another machine that's why netstat is not showing anything listening on 50090. I'm not sure if it's an Ambari issue or not I'll have to dig deeper to find the root cause. Thanks for reporting this.

**Comment by keyki** [comment]
Anyway we'll introduce NN HA so SN won't be allowed thus we'll remove the lambda blueprint as well.
