### ISSUE TITLE
Issues deploying the cloudbreak API

### ISSUE THREAD

**Issue by liammac** [sequenceiq/cloudbreak#474]
Using Boot2Docker on OS X and running into issues deploying cloudbreak using the instructions in the README

start_cloudbreak.sh

Seem to fail when trying to start up the cloudbreak container itself 

Logs from that container show this error

```java
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'stackConverter': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private java.lang.String com.sequenceiq.cloudbreak.converter.StackConverter.awsImage; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'cb.aws.ami.map' in string value "${cb.aws.ami.map}"
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:292)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1185)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:304)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:300)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:195)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:703)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:760)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:120)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:648)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:311)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:909)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:898)
        at com.sequenceiq.cloudbreak.CloudbreakApplication.main(CloudbreakApplication.java:14)
        ... 6 more
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private java.lang.String com.sequenceiq.cloudbreak.converter.StackConverter.awsImage; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'cb.aws.ami.map' in string value "${cb.aws.ami.map}"
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:508)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:87)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:289)
        ... 22 more
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'cb.aws.ami.map' in string value "${cb.aws.ami.map}"
        at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:174)
        at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:126)
        at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:194)
        at org.springframework.core.env.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:158)
        at org.springframework.context.support.PropertySourcesPlaceholderConfigurer$2.resolveStringValue(PropertySourcesPlaceholderConfigurer.java:175)
        at org.springframework.beans.factory.support.AbstractBeanFactory.resolveEmbeddedValue(AbstractBeanFactory.java:802)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:871)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:858)
```

**Comment by keyki** [comment]
I think the start_cloudbreak.sh hasn't been updated with the new env variables for a while now, but we're working on a new deployment process (a much better one with auto discovery) and it should be ready today or early next week. Sorry for the inconvenience.

**Comment by keyki** [comment]
Hi @liammac,

We've just created a new [repository](https://github.com/sequenceiq/cloudbreak-deployment) which contains the scripts to launch Cloudbreak on different environments. You can use the script in the local folder to spin up the stack on your laptop. 

You'll have to rename the env_props.sh.sample to env_props.sh and fill it. Besides that you'll need a public ip address to set it [here](https://github.com/sequenceiq/cloudbreak-deployment/blob/master/local/start.sh#L4). For that you can use `ngrok 8080`. The UI will launch on port 3000 so you need to create a port forward to the host from Virtualbox, but we'll change that soon to bind to the bridge address.
