### ISSUE TITLE
Openstack credential create failed : Internal server error

### ISSUE THREAD

**Issue by mike00151** [sequenceiq/cloudbreak#602]
Hello

I am using cloudbreak deployer

And I failed to credential my private openstack.

It appears "Openstack credential create failed : Internal server error" on UI

here is the logs from cdb logs commands

```

cloudbreak_1    | 2015-05-01 07:35:16,845 [http-nio-8080-exec-6] serverError:93 ERROR c.s.c.c.ExceptionControllerAdvice - [owner:cloudbreak] [type:cloudbreakLog] [id:undefined] [name:cb] Failed to convert from type com.sequenceiq.cloudbreak.controller.json.CredentialJson to type com.sequenceiq.cloudbreak.domain.OpenStackCredential for value 'com.sequenceiq.cloudbreak.controller.json.CredentialJson@6dfa7248'; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [org.jasypt.encryption.pbe.PBEStringCleanablePasswordEncryptor] is defined: expected single matching bean but found 2: pbeStringCleanablePasswordEncryptor,encryptor
cloudbreak_1    | org.springframework.core.convert.ConversionFailedException: Failed to convert from type com.sequenceiq.cloudbreak.controller.json.CredentialJson to type com.sequenceiq.cloudbreak.domain.OpenStackCredential for value 'com.sequenceiq.cloudbreak.controller.json.CredentialJson@6dfa7248'; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [org.jasypt.encryption.pbe.PBEStringCleanablePasswordEncryptor] is defined: expected single matching bean but found 2: pbeStringCleanablePasswordEncryptor,encryptor
cloudbreak_1    |       at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:41) ~[spring-core-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:174) ~[spring-core-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:158) ~[spring-core-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at com.sequenceiq.cloudbreak.controller.CredentialController.convert(CredentialController.java:174) ~[cloudbreak.jar!/:na]
cloudbreak_1    |       at com.sequenceiq.cloudbreak.controller.CredentialController.createCredential(CredentialController.java:156) ~[cloudbreak.jar!/:na]
cloudbreak_1    |       at com.sequenceiq.cloudbreak.controller.CredentialController.savePrivateCredential(CredentialController.java:55) ~[cloudbreak.jar!/:na]
cloudbreak_1    |       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_75]
cloudbreak_1    |       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_75]
cloudbreak_1    |       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_75]
cloudbreak_1    |       at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_75]
cloudbreak_1    |       at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:215) ~[spring-web-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132) ~[spring-web-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104) ~[spring-webmvc-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:749) ~[spring-webmvc-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:689) ~[spring-webmvc-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:83) ~[spring-webmvc-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:938) ~[spring-webmvc-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:870) ~[spring-webmvc-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:961) [spring-webmvc-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:863) [spring-webmvc-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at javax.servlet.http.HttpServlet.service(HttpServlet.java:646) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:837) [spring-webmvc-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at javax.servlet.http.HttpServlet.service(HttpServlet.java:727) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-embed-websocket-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilter(WebRequestTraceFilter.java:115) [spring-boot-actuator-1.0.2.RELEASE.jar!/:1.0.2.RELEASE]
cloudbreak_1    |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration$ApplicationContextFilterConfiguration$1.doFilterInternal(EndpointWebMvcAutoConfiguration.java:137) [spring-boot-actuator-1.0.2.RELEASE.jar!/:1.0.2.RELEASE]
cloudbreak_1    |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:108) [spring-web-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:103) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:154) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at com.sequenceiq.cloudbreak.conf.SecurityConfig$ScimAccountGroupReaderFilter.doFilterInternal(SecurityConfig.java:154) [cloudbreak.jar!/:na]
cloudbreak_1    |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:108) [spring-web-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationProcessingFilter.doFilter(OAuth2AuthenticationProcessingFilter.java:140) [spring-security-oauth2-2.0.3.RELEASE.jar!/:na]
cloudbreak_1    |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:110) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:57) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:108) [spring-web-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:50) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:108) [spring-web-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77) [spring-web-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:108) [spring-web-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.springframework.boot.actuate.autoconfigure.MetricFilterAutoConfiguration$MetricsFilter.doFilterInternal(MetricFilterAutoConfiguration.java:85) [spring-boot-actuator-1.0.2.RELEASE.jar!/:1.0.2.RELEASE]
cloudbreak_1    |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:108) [spring-web-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:683) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1721) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1679) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_75]
cloudbreak_1    |       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_75]
cloudbreak_1    |       at java.lang.Thread.run(Thread.java:745) [na:1.7.0_75]
cloudbreak_1    | Caused by: org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [org.jasypt.encryption.pbe.PBEStringCleanablePasswordEncryptor] is defined: expected single matching bean but found 2: pbeStringCleanablePasswordEncryptor,encryptor
cloudbreak_1    |       at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:970) ~[spring-beans-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at org.springframework.context.annotation.ContextAnnotationAutowireCandidateResolver$1.getTarget(ContextAnnotationAutowireCandidateResolver.java:82) ~[spring-context-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:187) ~[spring-aop-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at com.sun.proxy.$Proxy117.encrypt(Unknown Source) ~[na:na]
cloudbreak_1    |       at com.sequenceiq.cloudbreak.converter.JsonToOpenStackCredentialConverter.convert(JsonToOpenStackCredentialConverter.java:25) ~[cloudbreak.jar!/:na]
cloudbreak_1    |       at com.sequenceiq.cloudbreak.converter.JsonToOpenStackCredentialConverter.convert(JsonToOpenStackCredentialConverter.java:12) ~[cloudbreak.jar!/:na]
cloudbreak_1    |       at org.springframework.core.convert.support.GenericConversionService$ConverterAdapter.convert(GenericConversionService.java:353) ~[spring-core-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:35) ~[spring-core-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       ... 88 common frames omitted
uluwatu_1       | POST /user/credentials 500 173.232 ms - 35

```

Thanks

**Comment by keyki** [comment]
Hi,

This issue has been fixed, but I think the Cloudbreak version which the deployer is using does not contain this fix. Thanks for reporting this, we'll update it to use the latest stable versions.

**Comment by mike00151** [comment]
Thank you very much for the prompt reply/

It looks like something fail in docker container.

Could you please tell me when will update the latest stable versions ?

Thanks again.

**Comment by keyki** [comment]
We'll do the update soon, but can you please verify that you are using the latest version of the deployer? `cbd version` supposed to be `0.1.0`. If not you can update it with `cbd update` and deploy the CB again.

**Comment by mike00151** [comment]
Thanks for your reply.

Here is my result of ```cbd version``` command.

```
0.1.0-master-f7c9e67
latest version:
0.1.0
```

My cbd version is 0.1.0 already.

**Comment by lalyos** [comment]
Hi Mike,

Thanks for reporting. If this issue is deployer related, lets move it to https://github.com/sequenceiq/cloudbreak-deployer/issues

I would advice to use the *release* version, not the latest from master.
```
cbd update
```

after that please delete (or backup) both yml file
```
rm -rf *.yml
```

regenerate the yam files, and restart containers:

```
cbd generate
cbd start
cbd logs
```
